# Generated by Django 5.0.6 on 2024-05-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5')], max_length=3)),
                ('colored', models.CharField(choices=[('black_white', 'Ч/Б'), ('color', 'Цветное')], max_length=20)),
                ('sides', models.IntegerField(choices=[(1, '1 сторона'), (2, '2 стороны')])),
                ('paper_type', models.IntegerField(choices=[(80, '80 г/м²'), (90, '90 г/м²'), (120, '120 г/м²')])),
                ('extra_info', models.TextField()),
                ('amount', models.PositiveIntegerField(default=1)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='product_images')),
            ],
        ),
    ]
