# Generated by Django 5.0.6 on 2024-05-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_id_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
