# Generated by Django 4.2.13 on 2024-06-04 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.AlterField(
            model_name='product',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=100)),
                ('colored', models.CharField(max_length=100)),
                ('sides', models.CharField(max_length=100)),
                ('paper_type', models.CharField(max_length=100)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('amount', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
