# Generated by Django 4.2.13 on 2024-06-04 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_remove_product_amount_alter_product_extra_info_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=100)),
                ('colored', models.CharField(max_length=100)),
                ('sides', models.CharField(max_length=100)),
                ('paper_type', models.CharField(max_length=100)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('amount', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('work_status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В процессе'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
