# Generated by Django 4.2.13 on 2024-06-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_bill_order_bill_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='order',
        ),
        migrations.DeleteModel(
            name='BillOrder',
        ),
        migrations.AddField(
            model_name='bill',
            name='order',
            field=models.ManyToManyField(to='shop.order'),
        ),
    ]
