# Generated by Django 4.2.13 on 2024-06-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_bill_order_delete_billorder_bill_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='order',
        ),
    ]
