# Generated by Django 4.2.13 on 2024-06-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_bill_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='order',
            field=models.ManyToManyField(related_name='bills', to='shop.order'),
        ),
    ]
